apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: genot-web-cert
  namespace: genot-web-ns
spec:
  dnsNames:
    - genot.frl
  secretName: genot-web-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer