apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: genot-web-hpa
  namespace: genot-web-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: genot-web
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Pods
    pods:
      metric:
        name: packets-per-second
      target:
        type: AverageValue
        averageValue: 1k
  - type: Object
    object:
      metric:
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        name: main-route
      target:
        type: Value
        value: 10k