apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: genot-webingress
spec:
  tls:
  - hosts:
    - genot.frl
    secretName: genot-webtls
  rules:
  - host: genot.frl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: genot-webservice
            port:
              number: 80
