apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: genot-web-ingress
  namespace: genot-web-ns
spec:
  tls:
  - hosts:
    - genot.frl
    secretName: genot-web-tls
  rules:
  - host: genot.frl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: genot-web-service
            port:
              number: 80
